##################################################################################
# Cloudify host pool built in types and plugins definitions.
##################################################################################

plugins:
  hostpool:
    executor: central_deployment_agent
    source: https://github.com/trnvsk/cloudify-host-pool-plugin/archive/1.2-no-delete-queues.zip

node_types:
  cloudify.hostpool.nodes.Host:
    derived_from: cloudify.nodes.Compute
    interfaces:
      cloudify.interfaces.worker_installer:
        install:
          implementation: agent_installer.worker_installer.tasks.install
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                key: { get_attribute: [SELF, key] }
                password: { get_attribute: [SELF, password] }
                port: { get_attribute: [SELF, port] }
                delete_amqp_queues: false
        start:
          implementation: agent_installer.worker_installer.tasks.start
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                key: { get_attribute: [SELF, key] }
                password: { get_attribute: [SELF, password] }
                port: { get_attribute: [SELF, port] }
                delete_amqp_queues: false
        stop:
          implementation: agent_installer.worker_installer.tasks.stop
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                key: { get_attribute: [SELF, key] }
                password: { get_attribute: [SELF, password] }
                port: { get_attribute: [SELF, port] }
                delete_amqp_queues: false
        uninstall:
          implementation: agent_installer.worker_installer.tasks.uninstall
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                key: { get_attribute: [SELF, key] }
                password: { get_attribute: [SELF, password] }
                port: { get_attribute: [SELF, port] }
                delete_amqp_queues: false
        restart:
          implementation: agent_installer.worker_installer.tasks.restart
          inputs:
            cloudify_agent:
              default:
                user: { get_attribute: [SELF, user] }
                key: { get_attribute: [SELF, key] }
                password: { get_attribute: [SELF, password] }
                port: { get_attribute: [SELF, port] }
                delete_amqp_queues: false
      cloudify.interfaces.lifecycle:
        create:
          implementation: hostpool.cloudify_hostpool_plugin.tasks.acquire
          inputs:
            service_url:
              description: >
                The url to hostpool service
              type: string
        delete:
          implementation: hostpool.cloudify_hostpool_plugin.tasks.release
          inputs:
            service_url:
              description: >
                The url to hostpool service
              type: string

  cloudify.hostpool.nodes.WindowsHost:
    derived_from: cloudify.hostpool.nodes.Host
    interfaces:
      cloudify.interfaces.worker_installer:
        install:
          implementation: windows_agent_installer.windows_agent_installer.tasks.install
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                password: { get_attribute: [SELF, password] }
                delete_amqp_queues: false
        start:
          implementation: windows_agent_installer.windows_agent_installer.tasks.start
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                password: { get_attribute: [SELF, password] }
                delete_amqp_queues: false
        stop:
          implementation: windows_agent_installer.windows_agent_installer.tasks.stop
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                password: { get_attribute: [SELF, password] }
                delete_amqp_queues: false
        uninstall:
          implementation: windows_agent_installer.windows_agent_installer.tasks.uninstall
          inputs:
            cloudify_agent: 
              default:
                user: { get_attribute: [SELF, user] }
                password: { get_attribute: [SELF, password] }
                delete_amqp_queues: false
        restart:
          implementation: windows_agent_installer.windows_agent_installer.tasks.restart
          inputs:
            cloudify_agent:
              default:
                user: { get_attribute: [SELF, user] }
                password: { get_attribute: [SELF, password] }
                delete_amqp_queues: false
